### ISSUE TITLE
Tensorflow model

### ISSUE THREAD

**Issue by cucuuumber** [denru01/netadapt#1]
Hi!

Is there a possibility that you provide tensorflow implementation of NetAdapt?
Or, is it possible to run that pytorch implementation on tensorflow saved_model or frozen graph?

Regards,
Piotrek

**Comment by denru01** [comment]
We don't currently have a plan for providing a Tensorflow implementation. If your model does not contain special operations, you may be able to use some tools to convert the model from Tensorflow to Pytorch.

**Comment by cucuuumber** [comment]
Thank you for answer.
